repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((homeassistant|pylint|script|tests)/.+)?[^/]+\.(py|pyi)$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [homeassistant>=2025.7.0]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args: [--rcfile=pyproject.toml]
